name: Miscellaneous From Conda
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Include $CONDA in $PATH
      run: |
        echo ::add-path::$CONDA/bin
        echo ::add-path::$CONDA/condabin
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov codecov
    - name: Install via Conda
      run: |
        conda install -c conda-forge -c rdkit -c nostrumbiodiscovery miscellaneous --yes
    - name: Test with pytest
      run: |
        python -m pytest --cov=./ tests/
